title: The Update Framework (TUF)
description: Like the S in HTTPS, a plug-and-play library for securing a software updater
google_analytics: 
show_downloads: false
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
