name: 🐞 Bug Report
description: Create a report to help us improve
title: "[Bug Report] - <title>"
labels: ["bug","Needs Triage"]

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to file a Bug report! Please fill out the report and replace the '<title>' text in the title with a short description of the issue.
  - type: textarea
    attributes:
      label: Describe the bug.
      description: "Enter a clear and concise description of the bug."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the steps to reproduce the behavior.
      description: "Clearly and concisely describe the steps to ensure that it can be reproduced and potentially fixed."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    attributes:
      label: Expected behavior.
      description: "Enter a clear and concise description of what you expected to happen."
  - type: textarea
    attributes:
      label: Screenshots.
      description: "If applicable, add screenshots to help explain your problem."
  - type: input
    attributes:
      label: Operating environment
      description: "What operating system and version are you using?"
      placeholder: |
        Ubuntu 20.04.1 LTS
    validations:
      required: true
  - type: dropdown
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: textarea
    attributes:
      label: Additional context
      description: "Add any other context or screenshots to clarify your suggestion here."
